# Generated by Django 5.1.1 on 2024-10-22 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Laporan', '0001_initial'),
        ('Orderan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pembayaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Metode_Pembayaran', models.CharField(max_length=50, null=True)),
                ('Status_Pembayaran', models.CharField(max_length=50, null=True)),
                ('Tanggal_Pembayran', models.DateField()),
                ('ID_Orderan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Orderan.orderan')),
            ],
        ),
    ]
