# Generated by Django 5.1.1 on 2024-10-22 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pembayaran', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pembayaran',
        ),
    ]
