# Generated by Django 5.1.1 on 2024-09-26 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Pengguna', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orderan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tanggal_Order', models.DateField()),
                ('Jenis_Orderan', models.CharField(max_length=50, null=True)),
                ('Ukuran_Orderan', models.CharField(max_length=50, null=True)),
                ('Jumlah_orderan', models.IntegerField(null=True)),
                ('Harga_Total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Status_Orderan', models.CharField(default='Belum Diproses', max_length=50)),
                ('ID_Pelanggan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pengguna.pelanggan')),
            ],
        ),
        migrations.CreateModel(
            name='HistoriOrderan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tanggal_Perubahan', models.DateTimeField(auto_now_add=True)),
                ('Status_Baru', models.CharField(max_length=50)),
                ('Catatan', models.TextField(blank=True, null=True)),
                ('ID_Orderan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Orderan.orderan')),
            ],
        ),
        migrations.CreateModel(
            name='GambarOrderan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=255, null=True)),
                ('Deskripsi', models.TextField(blank=True, null=True)),
                ('ID_Orderan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Orderan.orderan')),
            ],
        ),
    ]
