# Generated by Django 5.1.1 on 2024-09-26 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Orderan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pengiriman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tanggal_Kirim', models.DateField()),
                ('Status_Pengiriman', models.CharField(default='Sedang Diproses', max_length=50)),
                ('Alamat_Pengiriman', models.TextField()),
                ('ID_Orderan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Orderan.orderan')),
            ],
        ),
    ]
