# Generated by Django 5.1.1 on 2024-09-11 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nama_Admin', models.CharField(max_length=50, null=True)),
                ('Password', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pelanggan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nama_pelanggan', models.CharField(max_length=100, null=True)),
                ('Email', models.CharField(max_length=50, null=True)),
                ('No_Telepon', models.CharField(max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Orderan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tanggal_Order', models.DateField()),
                ('Jenis_Orderan', models.CharField(max_length=50, null=True)),
                ('Ukuran_Orderan', models.CharField(max_length=50, null=True)),
                ('Jumlah_orderan', models.IntegerField(null=True)),
                ('Harga_Total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ID_Pelanggan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminPemesanan_backend.pelanggan')),
            ],
        ),
        migrations.CreateModel(
            name='Pembayaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Metode_Pembayaran', models.CharField(max_length=50, null=True)),
                ('Status_Pembayaran', models.CharField(max_length=50, null=True)),
                ('Tanggal_Pembayran', models.DateField()),
                ('ID_Orderan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminPemesanan_backend.orderan')),
            ],
        ),
    ]
